# -*- coding: utf-8 -*-
"""Wildlife Monitoring System using Camera Traps

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcq9zMsPoaONFKyQMrQYy26JIbe3s2Np
"""

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Clone YOLOv5 Repository and Install Requirements
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

# Step 2: Import Libraries
import torch
from matplotlib import pyplot as plt
import os
from PIL import Image

# Step 3: Load the YOLOv5 Model (you can also use 'yolov5x' or 'yolov5m')
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # 'yolov5s' is small and fast

# Step 4: Upload an Image
from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
    img_path = filename

# Step 5: Run Object Detection
results = model(img_path)
results.print()  # Print results in text
results.show()   # Show image with boxes

# Optional: Save the output image
results.save()  # Saved in yolov5/runs/detect/exp